version: '3.7'

services: 
    web: 
        build: .
        image: strava-downloader
        container_name: strava-downloader
        ports:
            - 5000:5000
        env_file:
            - .env
        volumes:
          - .:/home/project